### ISSUE TITLE
initSMhypers deleted from Core/cov.py in 9d940f9

### ISSUE THREAD

**Issue by iahs** [marionmari/pyGPs#18]
initSMhypers deleted from Core/cov.py in 9d940f9
This breaks e.g. demo_Airline.

**Comment by marionmari** [comment]
hi iahs, 
thanks for pointing this out. I will look into this resp. let Dan know about it (as he implemented this kernel and demo). 
marion

**Comment by mathDR** [comment]
PR submitted.

**Comment by mathDR** [comment]
Please close after PR is merged...

**Comment by mathDR** [comment]
merged
