### ISSUE TITLE
 bug in getDerMatrix for RBFard kernels

### ISSUE THREAD

**Issue by gsagnol** [marionmari/pyGPs#25]
Hi,

first thank you for your efforts in developping and maintaining pyGPs !

There is a bug in getDerMatrix for RBFard kernels:
At line 922,
https://github.com/marionmari/pyGPs/blob/master/pyGPs/Core/cov.py#L922

_there should be a multiplication instead of a division, because ell is defined as 1/exp(hyp...)
_a trnasposition is missing, so that `` spdist.cdist(tem,tem,'sqeuclidean')  `` always returns 0 at the next line...

One way to fix the issue is to replpace this line as follows:
tem = np.atleast_2d(tem[:,der]).T

I think there is also a similar issue in the case ``mode='cross' `` below, because there is also a division there.

**Comment by alexfeld** [comment]
Hi, has this bug been verified/is there a fix for it?

**Comment by gsagnol** [comment]
Sorry, I planned to commit a fix, but I didnt find the time yet.

Am 12.04.2016 um 02:40 schrieb alexfeld:

**Comment by marionmari** [comment]
hi, thanks for pointing this out! if you commit a fix, I can merge it. Marion

**Comment by alexfeld** [comment]
I've added a proposed fix for this in #29

**Comment by marionmari** [comment]
Great! Thanks!
