### ISSUE TITLE
Hyperparameters Not Optimizing with RBFArd

### ISSUE THREAD

**Issue by tarlen5** [marionmari/pyGPs#32]
I posted a question in [stackoverflow](http://stackoverflow.com/questions/39211569/automatic-relevance-determination-failing-in-pygps) with all the details. If any of the developers is able to answer this question/issue, it would be much appreciated! Thanks.

**Comment by mathDR** [comment]
Hey @tarlen5 I am having trouble recreating your results.  

Specifically if I cd to the Demo/Classification folder and run the following script:
```python import numpy as np
import pyGPs

demo_data = np.load("classification_data.npz")
tx, ty, tz = demo_data['x'], demo_data['y'], demo_data['xstar']

print "training shape: ",tx.shape

k = pyGPs.cov.RBFard(log_ell_list=[0.05, 0.17], log_sigma=1.0)
model = pyGPs.GPC()
model.setPrior(kernel=k)
print "hyperparams before optimization: ",model.covfunc.hyp
model.getPosterior(tx, ty)
model.optimize(tx, ty)
print "hyperparams after optimization: ",model.covfunc.hyp


mat = model.covfunc.getDerMatrix(tx, mode='train', der=0)
print np.alltrue(mat == 0.0)

mat = model.covfunc.getDerMatrix(tx, mode='train', der=1)
print np.alltrue(mat == 0.0)

mat = model.covfunc.getDerMatrix(tx, mode='train', der=2)
print np.alltrue(mat == 0.0)```

I get the results:

training shape:  (120, 2)
hyperparams before optimization:  [0.05, 0.17, 1.0]
Number of line searches 13
hyperparams after optimization:  [0.14169904264220798, 0.3390428179423049, 1.4957018577266905]
False
False
False

**Comment by tarlen5** [comment]
@mathDR Thank you very much for your quick reply! I ran your test script and I am interestingly getting different output than you. Before running it, I also uninstalled the software using pip and then re-installed it just now again. Here is my output:

```
training shape:  (120, 2)
hyperparams before optimization:  [0.05, 0.17, 1.0]
hyperparams after optimization:  [0.05, 0.17, 1.2605943579433447]
True
True
False
```

I am missing the line about the line searches (I assume you manually added that in?) Perhaps it has to do with software dependency versions? My versions are: 

- scipy: 0.18.0
- numpy: 1.11.1
- python: 2.7.12

Are there any other software versions you can think of that pyGPs relies on?

**Comment by mathDR** [comment]
Okay, I bet I know the issue.  I don't know if the fix to the rbfard kernel was pushed to pypi (so you can pip install it).  If you pip uninstall, then git clone the repository, and run 
```python 
python setup.py install
```
You should be good.  (Make sure you set your python path in your .bashrc or .bash_profile file to point to where you cloned pyGPs.

@marionmari Can you comment on the latest pypi version?

**Comment by tarlen5** [comment]
Thank you for the help! That appears to be the problem. I installed and ran the setup.py script as you directed and I can reproduce your output now. I guess the problem now is that the correct version isn't pushed to pypi, as you say.

**Comment by mathDR** [comment]
Great.  I will close this and open another issue stating the new version needs to be pushed to pypi.  Thanks!
