### ISSUE TITLE
ImportError: No module named past.utils

### ISSUE THREAD

**Issue by JKBehrens** [marionmari/pyGPs#35]
Hello

I installed pyGPs using your script and also tried all the other ways (pip, cloning) mentioned in your manual. I'm working on Ubuntu 14.04 and python 2.7.6.

When I try to import pyGPs, I get an error that past.utils is missing. You are using this on several locations.... and I can't find anything except your code about it on google.

Thank you!
Jan

```
>>> import pyGPs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyGPs/__init__.py", line 2, in <module>
    from . import Optimization
  File "pyGPs/Optimization/__init__.py", line 2, in <module>
    from . import scg
  File "pyGPs/Optimization/scg.py", line 3, in <module>
    from past.utils import old_div
ImportError: No module named past.utils
```

**Comment by mathDR** [comment]
Hey JK, this is interesting.  past should have been installed when you pip installed pyGPs.  In any case, the repository is https://pypi.python.org/pypi/past/  and denotes an ability to write both python 2/3 code.  Thanks.  I will check the setup.py file to see if this is the case.

**Comment by JKBehrens** [comment]
Thanks for that hint, @mathDR! I installed future (I was looking for past before) via pip and now I am able to import pyGPs. Please feel free to close this Issue. Maybe I overlooked an error while installing.
All the best!
Jan

**Comment by mathDR** [comment]
Okay Jan, I updated the setup.py file, so after a git clone, running 
```python
python setup.py install
```
will install future if it isn't already in your path.
