### ISSUE TITLE
Get rid of print statements!

### ISSUE THREAD

**Issue by citibeth** [marionmari/pyGPs#41]
There are `print()` statements all over the code.  This causes pain for users of the library who, for whatever reason, don't want stuff printed to STDOUT.  Please consider an alternative:

1. No print statements
2. Use Python logging API

**Comment by mathDR** [comment]
Hey @citibeth thanks for the comment.  Perhaps you could generate a PR with logging activated?  That would be awesome!

**Comment by shansfolder** [comment]
I open a PR #42 for it.

**Comment by changlan** [comment]
Any update on this issue? Thanks!

**Comment by shansfolder** [comment]
merged. :) 
also fixed some python2/3 compatible issues.
