### ISSUE TITLE
Online Documentation 403 Error

### ISSUE THREAD

**Issue by ramaroberto** [marionmari/pyGPs#53]
The page left to access the [online documentation](http://www-ai.cs.uni-dortmund.de/weblab/static/api_docs/pyGPs/), is returning a 403 code and the message:

You don't have permission to access /weblab/static/api_docs/pyGPs/ on this server.

Best,
Roberto.

**Comment by marionmari** [comment]
Thanks for pointing this out. We are aware of that and we are working on finding a new place to host the documentation.

**Comment by marionmari** [comment]
Fixed.
